/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class yingyin_webcam_WebcamDriverFirei */

#ifndef _Included_yingyin_webcam_WebcamDriverFirei
#define _Included_yingyin_webcam_WebcamDriverFirei
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     yingyin_webcam_WebcamDriverFirei
 * Method:    initialize
 * Signature: (Ljava/nio/IntBuffer;I)V
 */
JNIEXPORT void JNICALL Java_yingyin_webcam_WebcamDriverFirei_initialize
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     yingyin_webcam_WebcamDriverFirei
 * Method:    captureNowNative
 * Signature: (Ljava/nio/IntBuffer;Ljava/nio/IntBuffer;II)V
 */
JNIEXPORT void JNICALL Java_yingyin_webcam_WebcamDriverFirei_captureNowNative
  (JNIEnv *, jobject, jobject, jobject, jint, jint);

/*
 * Class:     yingyin_webcam_WebcamDriverFirei
 * Method:    cleanUp
 * Signature: (Ljava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_yingyin_webcam_WebcamDriverFirei_cleanUp
  (JNIEnv *, jobject, jobject);

/*
 * Class:     yingyin_webcam_WebcamDriverFirei
 * Method:    setPropertyNative
 * Signature: (Ljava/nio/IntBuffer;II)V
 */
JNIEXPORT void JNICALL Java_yingyin_webcam_WebcamDriverFirei_setPropertyNative
  (JNIEnv *, jobject, jobject, jint, jint);

/*
 * Class:     yingyin_webcam_WebcamDriverFirei
 * Method:    getCurrentPropertyNative
 * Signature: (Ljava/nio/IntBuffer;ILjava/nio/IntBuffer;Ljava/nio/IntBuffer;)I
 */
JNIEXPORT jint JNICALL Java_yingyin_webcam_WebcamDriverFirei_getCurrentPropertyNative
  (JNIEnv *, jobject, jobject, jint, jobject, jobject);

/*
 * Class:     yingyin_webcam_WebcamDriverFirei
 * Method:    qeuryPropertyNative
 * Signature: (Ljava/nio/IntBuffer;ILjava/nio/IntBuffer;Ljava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_yingyin_webcam_WebcamDriverFirei_qeuryPropertyNative
  (JNIEnv *, jobject, jobject, jint, jobject, jobject);

/*
 * Class:     yingyin_webcam_WebcamDriverFirei
 * Method:    setAutoPropertyNative
 * Signature: (Ljava/nio/IntBuffer;I)V
 */
JNIEXPORT void JNICALL Java_yingyin_webcam_WebcamDriverFirei_setAutoPropertyNative
  (JNIEnv *, jobject, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
