/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class yingyin_webcam_WebcamDriverFirei_CameraControl */

#ifndef _Included_yingyin_webcam_WebcamDriverFirei_CameraControl
#define _Included_yingyin_webcam_WebcamDriverFirei_CameraControl
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
