/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_mit_yingyin_camera_CameraDriverFirefly */

#ifndef _Included_edu_mit_yingyin_camera_CameraDriverFirefly
#define _Included_edu_mit_yingyin_camera_CameraDriverFirefly
#ifdef __cplusplus
extern "C" {
#endif
#undef edu_mit_yingyin_camera_CameraDriverFirefly_FRAME_RATE
#define edu_mit_yingyin_camera_CameraDriverFirefly_FRAME_RATE 30L
/*
 * Class:     edu_mit_yingyin_camera_CameraDriverFirefly
 * Method:    getDeviceNames
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_edu_mit_yingyin_camera_CameraDriverFirefly_getDeviceNames
  (JNIEnv *, jclass);

/*
 * Class:     edu_mit_yingyin_camera_CameraDriverFirefly
 * Method:    initialize
 * Signature: (Ljava/nio/IntBuffer;IIZ)V
 */
JNIEXPORT void JNICALL Java_edu_mit_yingyin_camera_CameraDriverFirefly_initialize
  (JNIEnv *, jobject, jobject, jint, jint, jboolean);

/*
 * Class:     edu_mit_yingyin_camera_CameraDriverFirefly
 * Method:    captureNow
 * Signature: (Ljava/nio/IntBuffer;Ljava/nio/IntBuffer;II)V
 */
JNIEXPORT void JNICALL Java_edu_mit_yingyin_camera_CameraDriverFirefly_captureNow
  (JNIEnv *, jobject, jobject, jobject, jint, jint);

/*
 * Class:     edu_mit_yingyin_camera_CameraDriverFirefly
 * Method:    cleanUp
 * Signature: (Ljava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_edu_mit_yingyin_camera_CameraDriverFirefly_cleanUp
  (JNIEnv *, jobject, jobject);

/*
 * Class:     edu_mit_yingyin_camera_CameraDriverFirefly
 * Method:    increaseExposure
 * Signature: (Ljava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_edu_mit_yingyin_camera_CameraDriverFirefly_increaseExposure
  (JNIEnv *, jobject, jobject);

/*
 * Class:     edu_mit_yingyin_camera_CameraDriverFirefly
 * Method:    decreaseExposure
 * Signature: (Ljava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_edu_mit_yingyin_camera_CameraDriverFirefly_decreaseExposure
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
