/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class yingyin_webcam_WebcamDriverFirefly */

#ifndef _Included_yingyin_webcam_WebcamDriverFirefly
#define _Included_yingyin_webcam_WebcamDriverFirefly
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     yingyin_webcam_WebcamDriverFirefly
 * Method:    initialize
 * Signature: (Ljava/nio/IntBuffer;II)V
 */
JNIEXPORT void JNICALL Java_yingyin_webcam_WebcamDriverFirefly_initialize
  (JNIEnv *, jobject, jobject, jint, jint);

/*
 * Class:     yingyin_webcam_WebcamDriverFirefly
 * Method:    captureNow
 * Signature: (Ljava/nio/IntBuffer;Ljava/nio/IntBuffer;II)V
 */
JNIEXPORT void JNICALL Java_yingyin_webcam_WebcamDriverFirefly_captureNow
  (JNIEnv *, jobject, jobject, jobject, jint, jint);

/*
 * Class:     yingyin_webcam_WebcamDriverFirefly
 * Method:    cleanUp
 * Signature: (Ljava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_yingyin_webcam_WebcamDriverFirefly_cleanUp
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
